baseURL = "https://wepis.github.io/"
languageCode = "en-us"
title = "WEPIS"
theme = "github-style"
googleAnalytics = "G-394CC2TGGG"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Muhammad Harjun"
  description = "We Play in Sunday"
  github = "muhammadharjun"
  twitter = "M_Harjun"
  email = "muhammadharjun@gmail.com"
  keywords = "blog, google analytics"
  lastmod = true
  favicon = "/images/github.png"
  location = "Indonesia"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
